### ISSUE TITLE
Input plugin 'systemd' cannot be loaded

### ISSUE THREAD

**Issue by amorey** [aws/amazon-cloudwatch-logs-for-fluent-bit#10]
When I add a systemd input to my fluent bit config using the `amazon/aws-for-fluent-bit:1.2.0` docker image inside a kubernetes cluster I get the following error:
```
Input plugin 'systemd' cannot be loaded
```

Here's a configuration file that reproduces the problem:
```
[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name            systemd
    Tag             host.*
    Systemd_Filter  _SYSTEMD_UNIT=docker.service
    Path            /var/log/journal

[OUTPUT]
    Name   stdout
    Match  *
```

In order to fix the problem I rebuilt the docker image using this docker file and everything seems to be working fine now:
```
FROM golang:1.12 as go-build
RUN go get github.com/aws/amazon-kinesis-firehose-for-fluent-bit
WORKDIR /go/src/github.com/aws/amazon-kinesis-firehose-for-fluent-bit
RUN make release
RUN go get github.com/aws/amazon-cloudwatch-logs-for-fluent-bit
WORKDIR /go/src/github.com/aws/amazon-cloudwatch-logs-for-fluent-bit
RUN make release

FROM fluent/fluent-bit:1.2.2
COPY --from=go-build /go/src/github.com/aws/amazon-kinesis-firehose-for-fluent-bit/bin/firehose.so /fluent-bit/firehose.so
COPY --from=go-build /go/src/github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/bin/cloudwatch.so /fluent-bit/cloudwatch.so

# Optional Metrics endpoint
EXPOSE 2020

# Entry point
CMD ["/fluent-bit/bin/fluent-bit", "-e", "/fluent-bit/firehose.so", "-e", "/fluent-bit/cloudwatch.so", "-c", "/fluent-bit/etc/fluent-bit.conf"]
```

**Comment by PettitWesley** [comment]
I was able to reproduce this; fluent bit immediately quits with the message:

```
Input plugin 'systemd' cannot be loaded
Error: Configuration file contain errors. Aborting
```

I have no clue why this occurs... the only difference between our image and fluent/fluent-bit is that we use amazon linux as the base.

**Comment by PettitWesley** [comment]
It might have something do with this: https://github.com/fluent/fluent-bit/blob/master/Dockerfile#L65

**Comment by PettitWesley** [comment]
The Dockerfile here fixes this: https://hub.docker.com/r/amazon/aws-for-fluent-bit

We'll soon do a release of the image to push out the fix.

I'm a bit embarrassed by this bug; the root cause was that I had used the names in aptitude (debian) for several of the packages instead of their names in yum. That, and also some packages are needed both at compile time and runtime.

**Comment by amorey** [comment]
Awesome! Thanks for fixing this! Out of curiosity, why not inherit from the fluent-bit image in the aws-for-fluent-bit Dockerfile?

**Comment by PettitWesley** [comment]
@amorey As a general rule, we tend to base the images that we publish on Amazon Linux, as it's a Linux distribution that we maintain and can support through AWS Premium Support.  Constructing our own image gives us more control over the resulting content of the image, which we want for things like patching and compliance with the licenses of the other things in the image.

**Comment by amorey** [comment]
@PettitWesley Is this issue fixed in the latest release (1.2.2)?

**Comment by PettitWesley** [comment]
@amorey Yup! 

I updated the `1.2.2` and `latest` tags to include this fix.

**Comment by amorey** [comment]
Awesome! Thanks!

**Comment by amorey** [comment]
@PettitWesley I tried out v1.2.2 and I'm getting an error that I don't see with my custom docker image (referenced above). Here's a config that reproduces the error:

```
   [SERVICE]                                                                   
        Flush         1                                                         
        Log_Level     info                                                      
        Parsers_File  parsers.conf                                              

    [INPUT]                                                                     
        Name            systemd                                                 
        Tag             journald.*.${NODE_NAME}                                 
        Systemd_Filter  _SYSTEMD_UNIT=kubelet.service                           
        Path            /var/log/journal                                        
        DB              /tmp/flb-test-k8s.db                                    

    [OUTPUT]                                                                    
        Name cloudwatch                                                         
        Match *                                                                 
        region us-east-1                                                        
        auto_create_group true                                                  
        log_group_name fluent-bit-test                                          
        log_stream_prefix flb-k8s.
```

And here's the error from the logs (with private data [REDACTED]):

```
time="2019-09-30T15:08:29Z" level=error msg="[cloudwatch 0] InvalidParameterException: 2 validation errors detected: Value '[REDACTED]' at 'logStreamName' failed to satisfy constraint: Member must have length less than or equal to 512; Value '[REDACTED]' at 'logStreamName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^:*]*\n\tstatus code: 400, request id: [REDACTED]\n"
```

Do you recognize this error?
