### ISSUE TITLE
[fyi] helm/charts incubator/fluent-bit-aws

### ISSUE THREAD

**Issue by daniel-ciaglia** [aws/amazon-cloudwatch-logs-for-fluent-bit#11]
Hi, just fyi, I created a helm chart for your fluent-bit plugin.
https://github.com/helm/charts/pull/15830
Would you mind checking the content, documentation and references?

Cheers!

**Comment by mforutan** [comment]
Now there is a chart for [fluent-bit](https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit) in eks-charts repo which supports CloudWatch plugin.

**Comment by daniel-ciaglia** [comment]
🙏 I'll close this isue then (as the mentioned PR wasn't approved anyway)
