### ISSUE TITLE
[Feature Request] Changing log_retention_days should update the retention policy of the LogGroup

### ISSUE THREAD

**Issue by markussiebert** [aws/amazon-cloudwatch-logs-for-fluent-bit#121]
It should be possible to update the logretention period via the plugin. Trying it out introducing the log_retention_days option for an existing created LogGroup didn't changed the retention policy.

**Comment by davidnewhall** [comment]
This feature currently only sets the retention when it creates a new group. Setting it on existing groups would require an out-of-band routine to constantly check all groups that the plugin writes to, or it would require adding extra API calls per-log-line to check the group's retention. Neither of these sound like ideal solutions, and this may not be a feature that fits in this app very well. Thoughts?

**Comment by PettitWesley** [comment]
A simple solution would be to simply always set the retention in this function, even if the log group already exists: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/mainline/cloudwatch/cloudwatch.go#L565

I think that'd accomplish what most users want.

**Comment by davidnewhall** [comment]
Yeah totally. We could probably change [this line](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/67976ff4c32e0bd5f2238eca4d48511e265efa88/cloudwatch/cloudwatch.go#L585) to:
```golang
return output.setLogGroupRetention(e.group)
```

**Comment by PettitWesley** [comment]
This has been implemented and will go out in the next release.

**Comment by zhonghui12** [comment]
This has been included in recent release, please check it here: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.10.0.

Will close this issue. Thanks
