### ISSUE TITLE
how to use role based service accounts 

### ISSUE THREAD

**Issue by rojomisin** [aws/amazon-cloudwatch-logs-for-fluent-bit#137]
the chart creates a service account, but how does one specify the role arn for that service account?  not clear by the docs

https://github.com/aws/eks-charts/issues/395

**Comment by rojomisin** [comment]
I am using rbac service accounts in eks, some other helm charts create the service account and have a config key to specify a value or annotation of the role arn that the service account uses.

**Comment by PettitWesley** [comment]
Forgive me... I don't have deep EKS knowledge, but I am pretty sure that when you create an IAM service account, you attach a policy not a role: https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html

Are you trying to set up cross account access for Fluent Bit

**Comment by andynelson** [comment]
You can do this by setting the following in values.yaml
```
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::***YOUR AWS ACCOUNT NUMBER***:role/***NAME OF YOUR ROLE***
```

The role needs to trust the OIDC issuer for your cluster - put this into the role's trust relationship policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowFromOIDC",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::***YOUR AWS ACCOUNT NUMBER***:oidc-provider/oidc.eks.***REGION***.amazonaws.com/id/***ID***"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.***REGION***.amazonaws.com/id/***ID***:sub": "system:serviceaccount:***KUBERNETES NAMESPACE***:***SERVICE ACCOUNT NAME***"
        }
      }
    }
  ]
}
```

**Comment by hossain-rayhan** [comment]
Hi @rojomisin, I believe @andynelson's comment works for you. Are you still looking for an answer? This issue will be closed soon if we don't hear back. Thanks.
