### ISSUE TITLE
ignore sending a log key to cloudwatch

### ISSUE THREAD

**Issue by nuved** [aws/amazon-cloudwatch-logs-for-fluent-bit#149]
I'm using parser feature of fluent bit for sending my nginx logs to cloudwatch. sometimes nginx container produces some extra logs.

I couldn't find any way to prevent sent these garbage logs to cloudwatch. 
It should be better if I can ignore sending a specific key to cloudwatch.

something like this 
log_key_ignore log

**Comment by PettitWesley** [comment]
@nuved You want to remove some fields from logs? There are filter plugins for that. 

https://docs.fluentbit.io/manual/pipeline/filters/record-modifier
https://docs.fluentbit.io/manual/pipeline/filters/modify

Do those do what you need?

**Comment by hossain-rayhan** [comment]
Hi @nuved, are you still looking for a solution? This issue will be closed in 7 days if we don't hear back from you. Thanks.
