### ISSUE TITLE
Input plugin 'systemd' cannot be loaded Error: You must specify an output target. Aborting

### ISSUE THREAD

**Issue by ld-singh** [aws/amazon-cloudwatch-logs-for-fluent-bit#15]
I am using the below config with image 1.2.2 

  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-cloudwatch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name              systemd
        Tag               host.*
        Systemd_Filter    _SYSTEMD_UNIT=docker.service
        Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter    _SYSTEMD_UNIT=kubeproxy.service                
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  output-cloudwatch.conf: |
    [OUTPUT]
        Name cloudwatch
        Match   *
        region ${REGION}
        log_group_name /eks/${CLUSTER_NAME}/logs
        log_stream_prefix eks
        auto_create_group true

My fluent-bit DS are crashing with below error:

Fluent Bit v1.2.2
Copyright (C) Treasure Data

Input plugin 'systemd' cannot be loaded
Error: You must specify an output target. Aborting

Why its not able to detect the output for  systemd?

**Comment by PettitWesley** [comment]
@ld-singh I believe this is the same issue as #10.

We'll be doing a release to fix it very very soon.

**Comment by PettitWesley** [comment]
@ld-singh Sorry, I forgot to respond to this; the issue has been fixed in the latest image.
