### ISSUE TITLE
One uninterpolated log stream is always created

### ISSUE THREAD

**Issue by vsimon** [aws/amazon-cloudwatch-logs-for-fluent-bit#160]
Using the helm chart from: https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit
Chart version: 0.1.6
amazon-cloudwatch-logs-for-fluent-bit version: 2.7.0

With the values:

```
  values:
  - firehose:
      enabled: false
    kinesis:
      enabled: false
    elasticsearch:
      enabled: false
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.role_arn }}
    cloudWatch:
      logGroupName: /aws/eks/cluster/application
      logStreamName: $(kubernetes['namespace_name'])/$(kubernetes['container_name'])
      logStreamPrefix:
      logRetentionDays: 90
```

I see log streams show up that contain the namespace name/ container name.

But I also see one log stream with the name `kubernetes['namespace_name']/kubernetes['container_name']`

![image](https://user-images.githubusercontent.com/137727/111854115-e0298e80-88da-11eb-828a-1a2627bdab55.png)

The log contents look related to fluent bit:

```
{"log":"[2021/03/20 00:41:17] [ warn] [input] tail.0 paused (mem buf overlimit)\n","stream":"stderr","time":"2021-03-20T00:41:17.799911083Z"}
...
```

Can this be removed or renamed?

**Comment by vsimon** [comment]
After fluent-bit comes up the first time, kill one of the pods (`kubectl delete pod ... `), then when it comes up again, the log stream `kubernetes['namespace_name']/kubernetes['container_name']` is there.

**Comment by DrewZhang13** [comment]
Looks like aws for fluent bit has issue for Templating Log Group and Stream Names to replace the variable in template for this situation.

**Comment by PettitWesley** [comment]
@vsimon @DrewZhang13 We built a feature for this.

From this repo's readme: 

> default_log_group_name: This required variable is the fallback in case any variables in log_group_name fails to parse. Defaults to fluentbit-default.
default_log_stream_name: This required variable is the fallback in case any variables in log_stream_name fails to parse. Defaults to /fluentbit-default.

**Comment by vsimon** [comment]
Thanks @PettitWesley, I wasn't aware, that looks great, I'll give this a try.

**Comment by vsimon** [comment]
Thinking through this first a bit @PettitWesley. Those variables should be as you say defaulting to 'fluentbit-default' and '/fluentbit-default'. I checked and the helm chart is not setting it in its configuration values (it does not even expose those values). So the log stream name should be defaulting to '/fluentbit-default' when it fails to parse. It does not when the pod is killed. I see log streams with the name `$(kubernetes['namespace_name'])/$(kubernetes['container_name'])` like in the screenshot.

The cloudwatch configuration values inside the aws-for-fluent-bit pod in the file /fluent-bit/etc/fluent-bit.conf:

```
[OUTPUT]
    Name                  cloudwatch
    Match                 *
    region                us-east-1
    log_group_name        /aws/eks/cluster/application
    log_stream_name       $(kubernetes['namespace_name'])/$(kubernetes['container_name'])
    log_retention_days    90
    auto_create_group     true
```
 
Again, the repro case is:

- Install the helm chart with the values in the initial Issue report
- Kill one of the aws-for-fluent-bit pods (kubectl delete pod ... )

Expected log stream name: fluentbit-default
Actual log stream name: $(kubernetes['namespace_name'])/$(kubernetes['container_name'])

**Comment by PettitWesley** [comment]
@vsimon I think this is the problem:

> amazon-cloudwatch-logs-for-fluent-bit version: 2.7.0

Pretty sure that version is too old. With the latest version, with your config but logs that lack the necessary keys I get output like this:

```
[2021/03/29 05:13:03] [ info] [engine] started (pid=1)
[2021/03/29 05:13:03] [ info] [storage] version=1.0.6, initializing...
[2021/03/29 05:13:03] [ info] [storage] in-memory
[2021/03/29 05:13:03] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
INFO[0000] [cloudwatch 0] plugin parameter log_group_name = '/aws/eks/cluster/application'
INFO[0000] [cloudwatch 0] plugin parameter default_log_group_name = 'fluentbit-default'
INFO[0000] [cloudwatch 0] plugin parameter log_stream_prefix = ''
INFO[0000] [cloudwatch 0] plugin parameter log_stream_name = '$(kubernetes['namespace_name'])/$(kubernetes['container_name'])'
INFO[0000] [cloudwatch 0] plugin parameter default_log_stream_name = '/fluentbit-default'
INFO[0000] [cloudwatch 0] plugin parameter region = 'us-east-1'
INFO[0000] [cloudwatch 0] plugin parameter log_key = ''
INFO[0000] [cloudwatch 0] plugin parameter role_arn = ''
INFO[0000] [cloudwatch 0] plugin parameter auto_create_group = 'true'
INFO[0000] [cloudwatch 0] plugin parameter new_log_group_tags = ''
INFO[0000] [cloudwatch 0] plugin parameter log_retention_days = '90'
INFO[0000] [cloudwatch 0] plugin parameter endpoint = ''
INFO[0000] [cloudwatch 0] plugin parameter sts_endpoint = ''
INFO[0000] [cloudwatch 0] plugin parameter credentials_endpoint =
INFO[0000] [cloudwatch 0] plugin parameter log_format = ''
[2021/03/29 05:13:03] [ info] [sp] stream processor started
[0] dummy: [1616994783.377293540, {"message"=>"dummy"}]
[1] dummy: [1616994784.377267373, {"message"=>"dummy"}]
[2] dummy: [1616994785.377243735, {"message"=>"dummy"}]
[3] dummy: [1616994786.377272014, {"message"=>"dummy"}]
ERRO[0004] [cloudwatch 0] parsing log_stream_name template '$(kubernetes['namespace_name'])/$(kubernetes['container_name'])': kubernetes['namespace_name']: tag name not found
INFO[0007] [cloudwatch 0] Created log group /aws/eks/cluster/application
INFO[0007] [cloudwatch 0] Set retention policy on log group /aws/eks/cluster/application to 90d
INFO[0007] [cloudwatch 0] Created log stream /fluentbit-default in group /aws/eks/cluster/application
ERRO[0007] [cloudwatch 0] parsing log_stream_name template '$(kubernetes['namespace_name'])/$(kubernetes['container_name'])': kubernetes['namespace_name']: tag name not found
ERRO[0007] [cloudwatch 0] parsing log_stream_name template '$(kubernetes['namespace_name'])/$(kubernetes['container_name'])': kubernetes['namespace_name']: tag name not found
ERRO[0007] [cloudwatch 0] parsing log_stream_name template '$(kubernetes['namespace_name'])/$(kubernetes['container_name'])': kubernetes['namespace_name']: tag name not found
```

And when I look in CloudWatch, I see a log stream named `/fluentbit-default`. I don't see any log streams named `$(kubernetes['namespace_name'])/$(kubernetes['container_name'])`.

**Comment by vsimon** [comment]
~~Thanks @PettitWesley! If that is the case, then can we release a new version of aws/amazon-cloudwatch-logs-for-fluent-bit? Do you have the ability to do that?~~

~~The chart is the latest version and specifies the [latest tagged version](https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/Chart.yaml#L5) of `aws/amazon-cloudwatch-logs-for-fluent-bit` which currently is 1.6.0 released on 12/8/20.~~

**Comment by vsimon** [comment]
Nevermind, I see that there are newer tags available on docker hub. https://hub.docker.com/r/amazon/aws-for-fluent-bit/tags?page=1&ordering=last_updated

I'll give those a try! Thanks!

**Comment by PettitWesley** [comment]
@vsimon For release info, please always check here: https://github.com/aws/aws-for-fluent-bit/releases

For consuming the image, we highly recommend ECR Public gallery over docker hub: https://gallery.ecr.aws/aws-observability/aws-for-fluent-bit

**Comment by vsimon** [comment]
Great! Thanks, I'll try the ECR gallery.

Not sure if these are official but they are under the "aws" github namespace: https://github.com/aws/eks-charts
It seems they don't even use the ECR gallery you recommend nor are on the latest version yet.

```
image:
  repository: amazon/aws-for-fluent-bit
  tag: 2.7.0
  pullPolicy: IfNotPresent
```

**Comment by vsimon** [comment]
Thanks @PettitWesley 2.12.0 works perfectly.
