### ISSUE TITLE
Docker image for Fluent Bit 1.3

### ISSUE THREAD

**Issue by talawahtech** [aws/amazon-cloudwatch-logs-for-fluent-bit#19]
Hi,

Fluent Bit v1.3 was recently released and I have been looking forwards to making use of one of the features in that version (collectd support). I was just wondering if creating a new release of the docker image was on the roadmap and what the timeline might look like. Thanks.

**Comment by PettitWesley** [comment]
@talawahtech It's been released!

[amazon/aws-for-fluent-bit:1.3.2](https://hub.docker.com/layers/amazon/aws-for-fluent-bit/1.3.2/images/sha256-7537834438778d873eb3fbcb5c7cf419f15206cdfe291d1cc89467b22daaeb72)

**Comment by computeracer** [comment]
@PettitWesley  Where would we find the latest Dockerfile this is being built from?

**Comment by PettitWesley** [comment]
@computeracer Just open sourced the source code! 

You can see the Dockerfile, as well as our integration tests for the AWS Plugins.

https://github.com/aws/aws-for-fluent-bit
