### ISSUE TITLE
Logical conditions in log_group_name

### ISSUE THREAD

**Issue by Funkerman1992** [aws/amazon-cloudwatch-logs-for-fluent-bit#195]
I've been faced an issue when some pods have a different label value, for example when I templating the log groups names
`log_group_name      /aws/containerinsights/${CLUSTER_NAME}/$(kubernetes['namespace_name'])/$(kubernetes['labels']['app'])`

Some sub-values not only app, but it could also be k8s-app or app.kubernetes.io/component, how I could play with it for example on a regexp level using regexp OR condition like the character  `| ` is it possible?

**Comment by zhonghui12** [comment]
Hi @Funkerman1992,

This request will be tracked in our `aws-for-fluent-bit` repo: https://github.com/aws/aws-for-fluent-bit/issues/243. As there are two same issue, I will close this one and let's keep all updates in one issue. Thanks.
