### ISSUE TITLE
Question: Output Matching multiple tags

### ISSUE THREAD

**Issue by kevinjenks** [aws/amazon-cloudwatch-logs-for-fluent-bit#212]
If i was curious if there was a way to do this or if I need to experiment more with the regex but Im trying to capture the output for several different pods in eks fargate and push them into a single log group group by relevancy. 
```[OUTPUT]
        Name cloudwatch_logs
        Match *foo|bar|baz*
        region us-east-1
        log_group_name <log_group_name>
        log_stream_prefix from-fluent-bit-
        auto_create_group true 
```

Similarly with a date YYYYMMDD
```
    [OUTPUT]
        Name cloudwatch_logs
        Match *\b(\d{4})(0[1-9]|1[0-2])(0[1-9]|[12]\d|30|31)\b*
        region us-east-1
        log_group_name <log_group_name>
        log_stream_prefix from-fluent-bit-
        auto_create_group true
```

**Comment by zhonghui12** [comment]
Hi @kevinjenks, fluent bit now supports tag rewritten: https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag. I wonder if it will help in your case like rewriting the tag and then send the tag with same prefix to one log group?

**Comment by zhonghui12** [comment]
Going to close this issue as no response for a while. Please feel free to reopen it if there are more problems. Thanks.
