### ISSUE TITLE
Old logs and 24h batching limit

### ISSUE THREAD

**Issue by alexeykaplin** [aws/amazon-cloudwatch-logs-for-fluent-bit#29]
I am getting lots of errors on an initial log sync:
`
time="2019-11-25T11:46:49Z" level=error msg="[cloudwatch 0] InvalidParameterException: The batch of log events in a single PutLogEvents request cannot span more than 24 hours.\n\tstatus code: 400, request id: 9e371dc0-5efe-4803-91d9-e779cb6bc165\n"
`

Possible solution is an appropriate duration limiter, it can be introduced here:
https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/83d185c0414803aa5bb563e8e213a5e9c9b85f92/cloudwatch/cloudwatch.go#L207

**Comment by PettitWesley** [comment]
@alexeykaplin We appreciate contributions! Especially for small things like this.

**Comment by alexeykaplin** [comment]
https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/pull/32
