### ISSUE TITLE
Build issue on Ubuntu 18.04, 64-Bit Linux host

### ISSUE THREAD

**Issue by openedev** [aws/amazon-cloudwatch-logs-for-fluent-bit#43]
Hi,

Any idea about this build issue?

$ make
PATH=/home/jagan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin golint ./cloudwatch
mkdir -p ./bin
go build -buildmode c-shared -o ./bin/cloudwatch.so ./
fluent-bit-cloudwatch.go:23:2: cannot find package "github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/cloudwatch" in any of:
	/usr/lib/go-1.10/src/github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/cloudwatch (from $GOROOT)
	/home/jagan/go/src/github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/cloudwatch (from $GOPATH)
fluent-bit-cloudwatch.go:24:2: cannot find package "github.com/aws/amazon-kinesis-firehose-for-fluent-bit/plugins" in any of:
	/usr/lib/go-1.10/src/github.com/aws/amazon-kinesis-firehose-for-fluent-bit/plugins (from $GOROOT)
	/home/jagan/go/src/github.com/aws/amazon-kinesis-firehose-for-fluent-bit/plugins (from $GOPATH)
fluent-bit-cloudwatch.go:25:2: cannot find package "github.com/fluent/fluent-bit-go/output" in any of:
	/usr/lib/go-1.10/src/github.com/fluent/fluent-bit-go/output (from $GOROOT)
	/home/jagan/go/src/github.com/fluent/fluent-bit-go/output (from $GOPATH)
fluent-bit-cloudwatch.go:27:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/lib/go-1.10/src/github.com/sirupsen/logrus (from $GOROOT)
	/home/jagan/go/src/github.com/sirupsen/logrus (from $GOPATH)
Makefile:26: recipe for target 'bin/cloudwatch.so' failed
make: *** [bin/cloudwatch.so] Error 1

**Comment by PettitWesley** [comment]
@openedev What's your go version? I've seen this before when trying to build the plugin with a version of go that doesn't support go modules or has go modules turned off.

**Comment by openedev** [comment]
@PettitWesley 
$ go version
go version go1.10.4 linux/amd64

**Comment by openedev** [comment]
@PettitWesley fixed the issue.

$ go get
$ make

This step worked for me.

**Comment by PettitWesley** [comment]
@openedev Cool. Given that you're on 1.10, I'm surprised you didn't need to set the env var `GO111MODULE` to `on`.

Can we close this issue?
