### ISSUE TITLE
Not listed under output plugins in fluent-bit documentation

### ISSUE THREAD

**Issue by awsimaya** [aws/amazon-cloudwatch-logs-for-fluent-bit#45]
Any reason why this is not listed under [fluent-bit output plugins](https://github.com/fluent/fluent-bit-docs/tree/master/pipeline/outputs) official documentation?

**Comment by PettitWesley** [comment]
@awsimaya The official documentation is for plugins in the core of Fluent Bit (the core repository), that are included in the official fluent/fluent-bit Docker Hub image. This plugin is external, that is why it is not there.

I'm working on rewriting this plugin in C and contributing it to the core: https://github.com/fluent/fluent-bit/pull/2024

Once it is merged and released, that plugin will have official docs (and we'll put out some sort of long term deprecation notice on this plugin).

**Comment by hencrice** [comment]
Resolving because the reasoning was provided.
