### ISSUE TITLE
Dynamic Coudwatch Log Groups 

### ISSUE THREAD

**Issue by techdragon** [aws/amazon-cloudwatch-logs-for-fluent-bit#46]
Other than shipping it as a sidecar inside every application pod, or building a complex filtering configuration with potentially dozens of instances of the cloudwatch logs output plugin that is dependent on informing every node of every possible application that may or may not be scheduled on it in order to decide ahead of time where logs should go, there appears to be no way to use this plugin to route logs for multiple applications to _separate_ cloudwatch log groups based on the applications.

A perfect solution to my problem would be directly configuring the log group based on kubernetes annotations similar to how they have integrated this feature, https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#annotation-examples-in-pod-definition, but failing that it would be good to have some basic functionality to allow construction of a log_group + log_stream as the tag, and define a separating character/string/index and have the logs routed to multiple log groups based on their "log group prefix" so to speak.

**Comment by hossain-rayhan** [comment]
Hi @techdragon , thanks for creating this issue. It's a good feature request and from our side, we also had an earlier discussion regarding the support of dynamic log groups. However, at this moment I don't have an exact timeline for this work.

Also, I appreciate your proposed idea/solution for the work. Will update you after further investigation.

**Comment by sionsmith** [comment]
Further to the this discussion I have tried to implement some basic dynamic functionality by placing an environment variable inside the `amazon-cloudwatch-agent.toml` file however the JSON validation fails when starting the agent. Is there any work around for this?

**Comment by PettitWesley** [comment]
@sionsmith This repo is for the Fluent Bit CloudWatch integration, not the CloudWatch Agent. I will ask the CW Agent team what is the best way to ask a question to them (I think its the AWS forums).

As an aside, if your use case is just log collection (CW Agent is a great metrics collector, its log functionality is simpler), I highly recommend Fluent Bit with the plugin in this repo :)

Edit: AWS Forums is the right place for CW Agent questions, or contact AWS Support.
