### ISSUE TITLE
AWS console missing Options for S3 and path

### ISSUE THREAD

**Issue by Oegma2** [aws/amazon-cloudwatch-logs-for-fluent-bit#52]
In order to do advance routing with fluentbit, we need access to the ***options*** fields in the task-definition side of things, but not available from the console - see image below for a suggestion 

![aws_firelens_options](https://user-images.githubusercontent.com/6543872/84679186-4559e900-af31-11ea-9d25-92be572ee0ff.png)

The options I am looking at in the task-definition side see image below 

![aws_firelens_options2](https://user-images.githubusercontent.com/6543872/84679426-923dbf80-af31-11ea-83e0-70020606674b.png)

Would be really handy if the aws console provides options for either file, s3, and ability to use custom fluentbit images...

**Comment by PettitWesley** [comment]
@Oegma2 We're aware of this. This repo is not the best place to track this request; the [container-roadmap ](https://github.com/aws/containers-roadmap)is the right place. Can you close this and open it there?

**Comment by Oegma2** [comment]
@PettitWesley - Thanks for the quick response - Will close this ticket and open it on the container roadmap page - makes sense :)
