### ISSUE TITLE
Intrepolation of the log_group

### ISSUE THREAD

**Issue by pecigonzalo** [aws/amazon-cloudwatch-logs-for-fluent-bit#6]
In may cases the `log_group` is a factor of what this is logging, eg `instances/$SERVICENAME` I wonder if there is a way to interpolate that or make `log_group` get that from a key.

Thanks

**Comment by owlwalks** [comment]
some reference from _fluentd_ [equivalent plugin](https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs):

```
<match kubernetes.**>
 @type cloudwatch_logs
 message_keys log
 log_group_name_key group
 ...
 <buffer>
  ...
 </buffer>
</match>
```

I think what we can do is adding a **log_group_name_key** option, its value will depend on an arbitrary record field
