### ISSUE TITLE
InvalidParameterException: Log event too large

### ISSUE THREAD

**Issue by albertschwarzkopf** [aws/amazon-cloudwatch-logs-for-fluent-bit#85]
Hi,

we are using this tool in K8s as Daemonset and get the following error sometimes (it depends on which node the pod is running and which other pods are running on this node):

`time="2020-08-26T08:24:17Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 635616 
  bytes exceeds limit of 262144\n\tstatus code: 400, request id: 9d79f780-3842-4438-a73d-dc6cc54864c8\n"            
 [2020/08/26 08:24:17] [ warn] [engine] chunk '1-1598430244.412167060.flb' cannot be retried: task_id=2, input=tail 
 .0 > output=cloudwatch.0 
`

So I know that there is this limit in AWS CW: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CalculatePutEventsEntrySize.html 

Is it possible to handle this issue (e.g. truncation, ...)?

Best regards,
Albert

**Comment by albertschwarzkopf** [comment]
Opened the issue here: https://github.com/aws/aws-for-fluent-bit/issues/68

**Comment by hossain-rayhan** [comment]
I believe, this issue is more related to this plugin. Reopening it for investigation.

**Comment by PettitWesley** [comment]
I think we are not properly checking the record size in the plugin. This is possibly a bug.

**Comment by PettitWesley** [comment]
This bug also affects the core CloudWatch Logs plugin in Fluent Bit: https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch

**Comment by davidnewhall** [comment]
Hitting the maximum log event size of 256K. Batches can be up to 1M, but a single event can only be 256K.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CalculatePutEventsEntrySize.html

**Comment by davidnewhall** [comment]
Something like this to fix it? maybe....

In `output.AddEvent()`:
```
eventString := truncateEvent(string(data))
```

Elsewhere:
```
const maximumBytesPerEvent = 256000

// truncateEvent reduces an Event to the maximum of 256KB.
func truncateEvent(event string) string {
	var runeCount = 0

	for index := range strings.TrimSpace(event) {
		if runeCount++; runeCount >= maximumBytesPerEvent {
			return event[:index]
		}
	}

	return event
}
```

**Comment by PettitWesley** [comment]
@davidnewhall Looks good, but for performance, check `len(event)` first. In go I believe length is an attribute of string, so its fast lookup.

**Comment by davidnewhall** [comment]
That makes sense, Wes. I [did some testing](https://play.golang.org/p/nYVvqMS1E9M) and concluded that the above approach doesn't work correctly with unicode and will produce strings over 256KB. This seems to work better (and probably faster):

```
eventString := truncateEvent(bytes.TrimSpace(data))
```

```
// truncateEvent reduces an Event to the Cloudwatch maximum of 256KB.
func truncateEvent(event []byte) string {
	if len(event) <= maximumBytesPerEvent {
		return string(event)
	}

	return string(event[:maximumBytesPerEvent])
}
```

What I'm not sure of is if this string is the only thing that needs calculating. The docs mention the json gets calculated as part of the size too. I'll have to produce some large log lines and see if this works. ;) We may have to add an arbitrary number of bytes (as done in other calculations). I have two more branches ready to make PRs once my currently-open PR(s) are "handled." I'll add this bug fix to one of those.

**Update:**
Making `truncateEvent()` return the event byte count along with the string representation allows us to remove `effectiveLen()` and `cloudwatchLen()` - likely speeding up the whole operation.

```
perEventBytes          = 26
maximumBytesPerEvent   = 256000 - perEventBytes
```

```
// truncateEvent reduces an Event to the Cloudwatch maximum of 256KB.
func truncateEvent(event []byte) (string, int) {
	if len(event) <= maximumBytesPerEvent {
		return string(event), len(event) + perEventBytes
	}

	return string(event[:maximumBytesPerEvent]), maximumBytesPerEvent + perEventBytes
}
```

**Comment by PettitWesley** [comment]
@davidnewhall LGTM

**Comment by PettitWesley** [comment]
Also, FYI, it's very hard to properly test large log lines. Docker truncates logs at 16 KB. Which means, until we implement generic log record concatenation in fluent bit, you can't get logs bigger than 16 KB with ECS/FireLens. The only way right now to test large logs is with log files and the in_tail plugin with proper settings.

**Comment by davidnewhall** [comment]
I don't really follow where "Docker truncates logs at 16KB" happens. 

My setup: fluentbit runs in Fargate with a second nginx container in the task definition. Fluentbit has only the syslog input active, listening on a socket file. Nginx listens for TCP requests using TLS and sends them to the socket file. Fluentbit then outputs them to CloudWatch. My test (when I get to it), should simply be `echo long line here | logger` from a Linux system configured to send syslog to that nginx container. 

I'm not currently using FireLens. Maybe that's where you're suggesting the limitation is?

**Comment by PettitWesley** [comment]
@davidnewhall Yeah, in that setup this limitation wouldn't apply.

It's a fairly standard practice though in the container world to log to standard out. Docker captures the stdout stream and sends it to log drivers (In ECS FireLens, the Fluentd docker log driver, in Kubernetes, the JSON log file driver). Docker truncates messages from stdout at 16 KB.

Fargate actually uses Containerd, which I think might not do any truncating (but I should check to be sure), but Fargate [FireLens re-uses code from Docker](https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/blob/master/logger/fluentd/logger.go#L24), which I think means the truncation still happens, not sure. I guess I don't entirely know how Fargate works anymore.
