### ISSUE TITLE
[Feature Request] Automatically re-create CloudWatch log groups and log streams if they have been deleted.

### ISSUE THREAD

**Issue by Amazonchaoyih** [aws/amazon-cloudwatch-logs-for-fluent-bit#95]
FireLens supports automatically creating CloudWatch Logs groups and log stream during start-up. However, if the log groups and streams are deleted afterwards, they will not be recreated by FireLens. All the logs will be lost.

**Comment by davidnewhall** [comment]
I was thinking about this today. Adding this shouldn't be too much work.

**Comment by zhonghui12** [comment]
It is released as part of https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.9.0.
