### ISSUE TITLE
Fallback log group and stream names

### ISSUE THREAD

**Issue by PettitWesley** [aws/amazon-cloudwatch-logs-for-fluent-bit#99]
@davidnewhall's awesome new formatting code means you can make the log stream and group names pretty much anything.

But what if something goes wrong?

As shown here, the plugin will make the names using the keys it couldn't find: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/issues/16#issuecomment-698776592

This is probably ok. But the ideal user experience would be to have a fallback log stream or group names that would be used if the necessary keys are not found in the logs.

**Comment by PettitWesley** [comment]
@davidnewhall Is this possible with the template code/library?

**Comment by davidnewhall** [comment]
I think adding a new key, like `default_log_group_name` and `default_log_stream_name` are the best options for that. I might be thinking too narrow here? That would require adjusting the method(s) a bit so they return some sort of error when a _provided_ variable is not found in the data map/json.

EDIT: For the log stream, we can use `log_stream_prefix` as a backup too. I toyed with this idea as I was making those changes originally, and I wasn't quite sure the best way to handle it. I suppose falling back to that if any of the keys are missing would be ideal.

**Comment by davidnewhall** [comment]
This can be closed. We have fallback log and stream names now. Documented in the [README](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/66b25a6ac3e7b52cb570004ce53937458fcea9ad/README.md)  as `default_log_group_name` and `default_log_stream_name`.

**Comment by PettitWesley** [comment]
Thanks!
